# Generated by Django 4.2.6 on 2023-10-17 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unternehmen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nachname', models.CharField(max_length=100)),
                ('steuernummer', models.CharField(max_length=20)),
                ('steuerklasse', models.IntegerField()),
                ('iban', models.CharField(max_length=34)),
                ('geburtsdatum', models.DateField()),
                ('eintritt', models.DateField()),
                ('austritt', models.DateField(blank=True, null=True)),
                ('sozialversicherungsnummer', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('email_passwort', models.CharField(max_length=100)),
                ('transportmittel', models.CharField(max_length=50)),
                ('telefonnummer', models.CharField(max_length=15)),
                ('ubereats_passwort', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('vertragsart', models.CharField(max_length=50)),
                ('sign', models.CharField(max_length=100)),
                ('uberaccount', models.CharField(max_length=100)),
                ('standort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mitarbeiter', to='hrm_app.unternehmen')),
            ],
        ),
        migrations.CreateModel(
            name='Dokument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=100)),
                ('datei', models.FileField(upload_to='dokumente/')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dokumente', to='hrm_app.personal')),
            ],
        ),
    ]
