# Generated by Django 4.2.6 on 2023-10-17 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_app', '0002_alter_personal_sozialversicherungsnummer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='eintritt',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personal',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='personal',
            name='email_passwort',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personal',
            name='geburtsdatum',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personal',
            name='iban',
            field=models.CharField(blank=True, max_length=34, null=True),
        ),
        migrations.AlterField(
            model_name='personal',
            name='nachname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personal',
            name='sign',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personal',
            name='sozialversicherungsnummer',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='SV-Nummer'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='standort',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mitarbeiter', to='hrm_app.unternehmen'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personal',
            name='steuerklasse',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personal',
            name='steuernummer',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='personal',
            name='telefonnummer',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='personal',
            name='transportmittel',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personal',
            name='uberaccount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personal',
            name='ubereats_passwort',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personal',
            name='vertragsart',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
