# Generated by Django 4.2.6 on 2023-10-17 21:29

from django.db import migrations, models
import hrm_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_app', '0003_alter_personal_eintritt_alter_personal_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokument',
            name='datei',
            field=models.FileField(upload_to=hrm_app.models.get_upload_to),
        ),
    ]
